---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.1.111
    path: /var/nfs
