---
apiVersion: v1
kind: Pod
metadata:
  name: dev6-vault
  namespace: vault
  labels:
    app: dev6-vault
spec:
  containers:
  - name: vault
    image: vault
    ports:
    - containerPort: 8200
      protocol: TCP
